version: '3'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root@123
      - APP_DB_USER=docker
      - APP_DB_PASS=docker@123
      - APP_DB_NAME=events
    volumes:
      - ./database:/docker-entrypoint-initdb.d/
      - pg-data:/var/lib/postgresql/data
    networks:
       - crud-app
    ports:
      - 5432:5432
  crud-app-go:
    image: crud-app-go:v1.6.0-1-gd79d2fd
    depends_on:
      - postgres
    volumes:
      - ./config.yaml:/app/config/config.yaml
    ports:
      - 8081:8080
    networks:
       - crud-app

volumes:
  pg-data:

networks:
  crud-app: