apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-app-go-deployment
  labels:
    app: crud-app-go
spec:
  replicas: 3
  selector:
    matchLabels:
      app: crud-app-go
  template:
    metadata:
      labels:
        app: crud-app-go
    spec:
      containers:
      - name: crud-app-go
        image: crud-app-go:v1.6.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: config
            mountPath: /app/config
      volumes:
      - name: config
        configMap:
          name: crud-app-config-go