apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-app-go-deployment
  labels:
    app: crud-app-go
spec:
  replicas: 3
  selector:
    matchLabels:
      app: crud-app-go
  template:
    metadata:
      labels:
        app: crud-app-go
    spec:
      containers:
      - name: crud-app-go
        image: srimaln91/crud-app:v3
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        command:
        - "/app/crud-app-linux-amd64"  # Entrypoint matches the binary path in the Dockerfile
        args:
        - "--config=/app/config/config.yaml"  # Argument for the config file
        volumeMounts:
        - name: config
          mountPath: /app/config
      volumes:
      - name: config
        configMap:
          name: crud-app-config-go
